language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install --user -r requirements.txt
  - pip install --user codecov
  - pip install .
# command to run tests
script: nose2 --with-coverage

after_success:
  - codecov
